import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import StateProvider from "@/context/provider";
import { FilterProvider } from "@/context/filter-context";
import { getItems } from "./actions/actions";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialItems = await getItems();

  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased dark`}>
        <StateProvider initialItems={initialItems}>
          <FilterProvider>
            <main className="min-h-screen">
              {children}
            </main>
          </FilterProvider>
        </StateProvider>
      </body>
    </html>
  );
}
