import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import StateProvider from "@/context/provider";
import { getItems } from "./actions/actions";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialItems = await getItems();

  return (
    <html lang="en">
      <StateProvider initialItems={initialItems}>
        <body className={`${montserrat.variable} antialiased dark`}>
          {children}
        </body>
      </StateProvider>
    </html>
  );
}
