import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import { FilterProvider } from "@/context/filter-context";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased dark`}>
        <FilterProvider>
          <main className="min-h-screen">
            {children}
          </main>
          <Toaster richColors position="top-center" />
        </FilterProvider>
      </body>
    </html>
  );
}
